Week11 php
Lidemy/mentor-program-5th-oack7426 pull request #12
Opened 2021-08-01 13:22 UTC by oack7426

再麻煩助教批改了，兩個作業沒有按照設計稿去刻畫，所以操作流程略有些不同
http://mentor-program.co/mtr04group4/oack7426/hw11/hw1/
http://mentor-program.co/mtr04group4/oack7426/hw11/hw2/

2021-08-06 11:33 UTC, cwc329 commented
請給我 admin 帳號，
這樣我才可以測試。

2021-08-07 04:14 UTC, oack7426 commented
> 請給我 admin 帳號，
> 這樣我才可以測試。

好的，很抱歉忘記提供
帳號 admin
密碼 admin

2021-08-11 11:53 UTC, cwc329 requested changes

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/admin.php
> +          $sql = "SELECT oack7426_comments.nickname,oack7426_comments.content,oack7426_comments.created_at, oack7426_users.role FROM oack7426_comments INNER JOIN oack7426_users ON oack7426_comments.u
sql 可以排版一下。
另外 table 可以用 alias，
這樣會比較簡潔。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/admin.php
> +                     <a href="./update_role.php?username=<?php echo $row['username'] ?>">修改</a>
不要用 username 當作 key 或者 index，
用 id。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/header.php
> +          echo $username.' 你好，';
XSS。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/update.php
> +              <textarea name="content"><?php echo $row['content'] ?></textarea>
從後台進入編輯頁面沒有原本的留言內容。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw2/article.php
> +  <title><?php echo $title ?></title>
XSS

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw2/article.php
> +    <h2> <?php echo $title ?></h2>
XSS

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw2/article.php
> +          <p><?php echo $content ?></p>
XSS

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/login.php
> +    }
這邊會卡在錯誤頁面，
使用者體驗很不好。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw2/handle_add.php
> +  $sql = "INSERT INTO oack7426_articles(title, content) VALUES ('$title','$content')";
這個 query 看起來怪怪的。

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw2/handle_login.php
> +  $result = $conn ->query($sql); //呼叫確定是否執行成功
已經用 prepared statement 呼叫了，
為何還要用 query？

2021-08-11 11:53 UTC, cwc329 commented on homeworks/week11/hw1/delete.php
> +  require_once('conn.php');
沒有權限驗證。

2021-08-11 11:55 UTC, cwc329 commented
太多 XSS 漏洞，
也有很多權限驗證問題，
這份作業完成度太低了，
請先依照 week11 自我檢討，
把所有 XSS, SQL injection 與權限漏洞修正，
再重新提交一次。

2021-08-11 11:55 UTC, closed without merging

2021-08-12 01:34 UTC, oack7426 commented
> 太多 XSS 漏洞，
> 也有很多權限驗證問題，
> 這份作業完成度太低了，
> 請先依照 week11 自我檢討，
> 把所有 XSS, SQL injection 與權限漏洞修正，
> 再重新提交一次。

感謝助教批改，想先請問修改完的作業要如何重新提交? 謝謝您。

2021-08-12 04:23 UTC, cwc329 commented
可以重新開啟這個 PR，
或者重發一個 PR 都可以，
然後再去學習系統交作業。