Week2 javascript
Lidemy/mentor-program-5th-oack7426 pull request #2
Opened 2021-04-17 14:33 UTC by oack7426

有看過作業檢討
hw2  保留了判斷 a-z 小寫的函式，雖然作業檢討有更直覺的寫法，但整體作業還是希望保留自己最初的思路在複習時比較好理解。

2021-04-18 05:42 UTC, cwc329 requested changes

2021-04-18 05:42 UTC, cwc329 commented on homeworks/week2/hw2.js
> +function checkEng(num){
為何要用 num？
傳完進來的會是一個 number 嗎？

2021-04-18 05:42 UTC, cwc329 commented on homeworks/week2/hw2.js
> +console.log(capitalize('hello'));
這題沒有過喔，
你有自己測試過程式碼嗎？

2021-04-18 05:42 UTC, cwc329 commented on homeworks/week2/hw6.md
> +5.重複 3 ~ 4 步驟，直到 i === arr.length ，到最後都沒有符合 if (arr[i] <= 0) 的條件式，結束此迴圈，繼續執行
要一步一步地寫出來，所以從第二圈迴圈開始到底是怎麼判斷的呢？

2021-04-18 05:42 UTC, cwc329 commented on homeworks/week2/hw6.md
> +9.重複 7~8 步驟，直到 arr[4] = 22 ，帶入判斷 (arr[i] !== arr[i-1] + arr[i-2]) 時， 22!== 13 + 8,條件成立， return 'invalid' 結束此迴圈也結束此function 程式
同第一個迴圈。

2021-04-18 05:43 UTC, cwc329 commented
hw2 沒有通過，而且變數命名有點奇妙。
hw6 沒有符合作業要求，請再寫得詳細一些。

2021-04-19 01:36 UTC, oack7426 commented on homeworks/week2/hw2.js
> +console.log(capitalize('hello'));
有測過，但看來測得不夠仔細
很抱歉造成助教的困擾

2021-04-19 01:36 UTC, oack7426 commented on homeworks/week2/hw6.md
> +5.重複 3 ~ 4 步驟，直到 i === arr.length ，到最後都沒有符合 if (arr[i] <= 0) 的條件式，結束此迴圈，繼續執行
好的

2021-04-19 01:38 UTC, oack7426 commented
> hw2 沒有通過，而且變數命名有點奇妙。
> hw6 沒有符合作業要求，請再寫得詳細一些。

很抱歉這次作業不夠細心造成助教困擾
想問作業修改後要如何通知助教再次批改? 謝謝您。

2021-04-19 01:48 UTC, oack7426 commented on homeworks/week2/hw2.js
> +function checkEng(num){
感謝助教注意，的確這裡命名num非常不恰當，改成str會好一些

2021-04-19 13:37 UTC, oack7426 commented
> hw2 沒有通過，而且變數命名有點奇妙。
> hw6 沒有符合作業要求，請再寫得詳細一些。

hw2 作業已修改也確實有測試通過
hw6 有寫得再詳細一點確實照程式的一行行去寫

再拜託助教批改了，感謝

2021-04-19 14:32 UTC, cwc329 approved these changes
GJ
恭喜，可以往下一週前進了

2021-04-19 14:32 UTC, cwc329 commented on homeworks/week2/hw5.js
> +  let str = [];
`str = []`
這也不太符合慣例，建議修改。

2021-04-19 14:32 UTC, cwc329 commented on homeworks/week2/hw2.js
這個空行建議拿掉

2021-04-19 14:32 UTC, merged

2021-04-20 08:04 UTC, oack7426 commented on homeworks/week2/hw5.js
> +  let str = [];
了解，感謝助教抓錯。

2021-04-20 08:05 UTC, oack7426 commented on homeworks/week2/hw2.js
好的，感謝助教抓錯

2021-04-20 08:05 UTC, oack7426 commented
> GJ
> 恭喜，可以往下一週前進了

感謝助教的批改 ヾ(*´∀ ˋ*)ﾉ